### ISSUE TITLE
Load MClust .t files into SpikeInterfaces

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/data-formats#14]
This is a prereq for issue #13 !

**Comment by hungtuchen** [comment]
Try M40-2020-04-28-CDOD11 & M40-2020-04-29-CDOD12 in /datavault/incoming/vStr-eyeblink/Pilot/M40 were recorded at 30 kHz probably?

**Comment by mvdm** [comment]
Yes, looks like you need to download the archive from those folders

**Comment by mvdm** [comment]
@transedward sounds like you've made some progress with this, can you post a link here to the code/instructions you have so far? what is left to do?

**Comment by hungtuchen** [comment]
There is minimal example here: https://github.com/vandermeerlab/data-formats/blob/master/loading_MClust_spikes.ipynb

I basically ported the mclust loader function from nept to this repo and change the way unit labels are extracted (to make uniquely identifiable for spike sorter comparison).
