### ISSUE TITLE
Create neo issue showing different timestamps depending on available files

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/data-formats#3]
Minimal working example is here: https://github.com/vandermeerlab/data-formats/blob/master/neo-nept-loading.ipynb

Concern is that the output timestamps for the same file are different depending on whether that file is loaded on its own or with other files present. This is undesirable because:
- inconsistent output for same data
- difficult/impossible to sync timestamps with outputs from processing not loaded with neo (e.g. MClust spike sorting)

**Comment by mvdm** [comment]
@yarikoptic is the 32kHz "WidebandTest" example data set publicly available for me to link to? (it's on smaug)

**Comment by yarikoptic** [comment]
Are you referring to http://datasets.datalad.org/?dir=/labs/mvdm/MotivationalT-v2/R050/R050-2014-03-31_raw?

**Comment by mvdm** [comment]
The one you link to has only .ntt spikes, not wideband continuous data. Hence the "WidebandTest" folder on incoming/mvdm on smaug.

**Comment by yarikoptic** [comment]
oh, on http://datasets.datalad.org/?dir=/labs/mvdm/WidebandTest now.  It is small, could have even gone to github directly ;-)

**Comment by mvdm** [comment]
Issue is up now on the neo repo: https://github.com/NeuralEnsemble/python-neo/issues/814
