### ISSUE TITLE
Run Kilosort2 on probe data

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/data-formats#5]
- [x] Set up linux box with GPU @mvdm 
- [x] Give Yarik admin privileges @mvdm
- [x] Get an example probe data set promoted (ideally 32kHz as well as .ntt) @jgmaz?
- [x] Install CUDA and MATLAB on linux box
- [x] Figure out how to add Neuronexus probe geometry as input to Kilosort @stottbot this will be interesting for you too!

Useful links:
-  https://github.com/MouseLand/Kilosort2

**Comment by mvdm** [comment]
Looks like there are 2 ways of going about this:
1) try to use spikeinterfaces (unclear to me how this will interface with MATLAB)
2) maybe simpler for now, check if we can get it to run in MATLAB by itself first before connecting with spikeinterfaces

**Comment by manimoh** [comment]
Modified KS2 pipeline using the [probe file](https://github.com/vandermeerlab/data-formats/blob/master/probe_files/NN_A4x2tet.prb) present [here](https://github.com/vandermeerlab/data-formats/blob/master/ks2_30kHz_continuous_withProbeFile.ipynb)!
